### ISSUE TITLE
Names of team members missing while mentioning the people who constructed this repository.

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/FSE-2012-FaultTracer-old#10]

**Comment by jodeck80** [comment]
It looks like most other repos only note the one owning person. @spshetty, do you agree? If so, I will close the issue.

**Comment by jodeck80** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2012-FaultTracer#10
