### ISSUE TITLE
Link to the original website missing.

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/FSE-2012-FaultTracer-old#2]

**Comment by jodeck80** [comment]
Original website is provided under "Official Project Page" and original source is provided under "original download link". No further action is needed. @spshetty, do you agree? If so, we can close the issue.

**Comment by jodeck80** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2012-FaultTracer#2
