### ISSUE TITLE
Full history of project is missing

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/FSE-2012-FaultTracer-old#3]

**Comment by jodeck80** [comment]
Project should have been migrated from bitbucket, https://bitbucket.org/zhanglm10/faulttracer/. Going to rename this repository with _old, and move to @jodeck80 personal account. Will create new repository with proper history.

**Comment by jodeck80** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2012-FaultTracer#3
